tap 'homebrew/bundle'

brew 'ack'
brew 'bash-completion'
brew 'composer'
brew 'coreutils'
brew 'git'
brew 'grc'                  # Needed for `ls` to work in ZSH apparently?
brew 'imagemagick'
brew 'libmemcache'
brew 'mariadb'
brew 'memcached'
brew 'node'
brew 'wget'
brew 'z'
